#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Composer autoload
require __DIR__.'/vendor/autoload.php';

// Create the application
$app = require_once __DIR__.'/bootstrap/app.php';

// Run the artisan command
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new ArgvInput,
    new Illuminate\Console\OutputStyle($input, new Symfony\Component\Console\Output\ConsoleOutput)
);

// Terminate
$kernel->terminate($input, $status);

exit($status);
